name: Ruff

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install ruff
      run: pip install ruff

    - name: Run ruff
      id: ruff_check
      run: |
        ruff format --check .
        if [ $? -ne 0 ]; then
          echo "Ruff found issues, attempting to fix..."
          ruff format .
        else
          echo "No formatting issues found."
        fi

    - name: Commit changes
      if: steps.ruff_check.outputs.reformatted == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Auto-format code with ruff"
        git push